# Generated by Django 3.0.6 on 2020-05-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('deadline', models.DateTimeField(db_index=True)),
                ('priority', models.CharField(choices=[('Высокий', 'Высокий'), ('Средний', 'Средний'), ('Низкий', 'Низкий')], max_length=20)),
                ('status', models.CharField(choices=[('Ожидает выполнения', 'Ожидает выполнения'), ('В процессе выполнения', 'В процессе выполнения'), ('Выполнена', 'Выполнена')], default='Ожидает выполнения', max_length=100)),
            ],
        ),
    ]
