# Generated by Django 3.0.6 on 2020-05-19 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('-created',)},
        ),
    ]
